### ISSUE TITLE
helm chart created but no pods deployed

### ISSUE THREAD

**Issue by darioneto** [patoarvizu/freqtrade-helm-chart#7]
Installing this chart on k8s v1.23.5 and despite the fact I can see it deployed on the helm list there is no pods/pvc/svc created. Any idea as to why that is?

**Comment by patoarvizu** [comment]
Both `.backtesting.enabled` and `.bot.enabled` are set to `false` by default in `values.yaml`, which means you have to explicitly set them to `true` in your release to see anything. Are you enabling them? I know this may seem counterintuitive but I did it so you wouldn't start doing live testing by accident.

Otherwise I believe the only things that would be created by default are two `ConfigMap`s and an `Ingress`, do you see those being installed?

**Comment by darioneto** [comment]
I've only enabled bot which is set to true. Ingres and backtesting are disabled as I don't need them. Only config maps are being installed, nothing else is. helm chart is listed as deployed.

**Comment by darioneto** [comment]
Thanks for your reply and sharing this chart by the way, ok after setting the bot to true the installation goes through. All good

**Comment by darioneto** [comment]
by the way, have you had any issues adding custom images with this deployment? I tried building through compose from develop and even installing dependencies manually with a commit, but both attempts failed with Exit code 1 and CrashLoopBackOff. This is very bizarre.

**Comment by patoarvizu** [comment]
Hey @darioneto Sorry for the late reply. I think you're all set and we can close this? I'll keep it open until you confirm.

And I haven't tried using custom images with this project. Do you mean a custom fork of freqtrade that you build locally?

**Comment by darioneto** [comment]
yeah, I've found the way around it, we can close it, all good thanks
